// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeEvent() (Event, error) {
	message := GetMessage()
	greeter := GetGreeter(message)
	event, err := GetEvent(greeter)
	if err != nil {
		return Event{}, err
	}
	return event, nil
}
